// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YFTimeTracker.Data;

#nullable disable

namespace YFTimeTracker.Data.Migrations
{
    [DbContext(typeof(YFTimeTrackerDbContext))]
    partial class YFTimeTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("YFTimeTracker.Core.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyPlaytimeLimitMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalGameId")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectoryKey")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyExecutableName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .HasColumnName("ExecutableName");

                    b.Property<string>("LegacyExecutablePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("ExecutablePath");

                    b.Property<string>("LegacyExecutablePathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("ExecutablePathKey");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeeklyPlaytimeLimitMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LegacyExecutablePathKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Games_ExecutablePathKey");

                    b.HasIndex("Name");

                    b.HasIndex("Source", "ExternalGameId")
                        .IsUnique()
                        .HasFilter("ExternalGameId IS NOT NULL");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.GameExecutable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutableName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExecutablePathKey")
                        .IsUnique();

                    b.HasIndex("GameId");

                    b.HasIndex(new[] { "GameId" }, "IX_GameExecutables_GameId_Primary")
                        .IsUnique()
                        .HasDatabaseName("IX_GameExecutables_GameId_Primary")
                        .HasFilter("IsPrimary = 1");

                    b.ToTable("GameExecutables", (string)null);
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BootSessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndedAtUtc");

                    b.HasIndex("GameId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex(new[] { "GameId" }, "IX_GameSessions_GameId_Open")
                        .IsUnique()
                        .HasDatabaseName("IX_GameSessions_GameId_Open")
                        .HasFilter("EndedAtUtc IS NULL");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.NotificationLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RelatedGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Kind", "ReferenceKey")
                        .HasFilter("ReferenceKey IS NOT NULL");

                    b.ToTable("NotificationLogEntries", (string)null);
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.GameExecutable", b =>
                {
                    b.HasOne("YFTimeTracker.Core.Models.Game", "Game")
                        .WithMany("Executables")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.GameSession", b =>
                {
                    b.HasOne("YFTimeTracker.Core.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("YFTimeTracker.Core.Models.Game", b =>
                {
                    b.Navigation("Executables");
                });
#pragma warning restore 612, 618
        }
    }
}
